name: Upstream Dispatch
on: [pull_request, create]

jobs:
  build:
    name: Dispatch to loterie
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        run: curl -X POST https://api.github.com/repos/sameo/loterie/dispatches -d '{"event_type":"eventType"}'


