name: Upstream Dispatch
on: [pull_request, create]

jobs:
  build:
    name: Dispatch to loterie
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        run: curl -X POST -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/sameo/loterie/dispatches -d '{"event_type":"eventType"}'


